export const SYNC_PROTOCOL_VERSION = 1 as const;

export * from './billing';

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

export type SyncCursor = {
  version: typeof SYNC_PROTOCOL_VERSION;
  position: string;
};

export type SyncOperation = {
  /** A globally unique, durable idempotency key generated by the client. */
  id: string;
  entityType: string;
  entityId: string;
  kind: string;
  payload: JsonObject;
  createdAt: string;
};

export type OperationBatch = {
  protocolVersion: typeof SYNC_PROTOCOL_VERSION;
  batchId: string;
  clientId: string;
  cursor?: SyncCursor;
  operations: SyncOperation[];
};

export const OPERATION_REJECTION_CODES = [
  'malformed_operation',
  'unauthorized',
  'forbidden',
  'conflict',
  'idempotency_key_reused',
  'server_error',
] as const;

export type OperationRejectionCode =
  (typeof OPERATION_REJECTION_CODES)[number];

export type RejectedOperation = {
  operationId: string;
  code: OperationRejectionCode;
  message: string;
  retryable: boolean;
};

export const CONFLICT_REASONS = [
  'concurrent_update',
  'server_deleted',
  'client_deleted',
] as const;

export type ConflictReason = (typeof CONFLICT_REASONS)[number];

export type ConflictRecord = {
  operationId: string;
  entityType: string;
  entityId: string;
  reason: ConflictReason;
  clientVersion: string | null;
  serverVersion: string | null;
  /** The authoritative server value for server-wins reconciliation. */
  serverRecord?: JsonObject;
  message: string;
};

export type OperationResult = {
  protocolVersion: typeof SYNC_PROTOCOL_VERSION;
  batchId: string;
  cursor: SyncCursor;
  acceptedOperationIds: string[];
  rejectedOperations: RejectedOperation[];
  conflicts: ConflictRecord[];
};

type UnknownRecord = Record<string, unknown>;

function record(value: unknown, name: string): UnknownRecord {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TypeError(`${name} must be an object`);
  }
  return value as UnknownRecord;
}

function stringField(value: UnknownRecord, field: string, owner: string): string {
  const candidate = value[field];
  if (typeof candidate !== 'string' || candidate.length === 0) {
    throw new TypeError(`${owner}.${field} must be a non-empty string`);
  }
  return candidate;
}

function booleanField(
  value: UnknownRecord,
  field: string,
  owner: string,
): boolean {
  const candidate = value[field];
  if (typeof candidate !== 'boolean') {
    throw new TypeError(`${owner}.${field} must be a boolean`);
  }
  return candidate;
}

function versionField(value: UnknownRecord, owner: string): 1 {
  if (value.protocolVersion !== SYNC_PROTOCOL_VERSION) {
    throw new TypeError(`${owner}.protocolVersion must be 1`);
  }
  return SYNC_PROTOCOL_VERSION;
}

function enumField<const Values extends readonly string[]>(
  value: UnknownRecord,
  field: string,
  owner: string,
  values: Values,
): Values[number] {
  const candidate = stringField(value, field, owner);
  if (!(values as readonly string[]).includes(candidate)) {
    throw new TypeError(`${owner}.${field} is not supported`);
  }
  return candidate as Values[number];
}

function nullableStringField(
  value: UnknownRecord,
  field: string,
  owner: string,
): string | null {
  if (value[field] === null) return null;
  return stringField(value, field, owner);
}

function parseJsonValue(value: unknown, name: string): JsonValue {
  if (
    value === null ||
    typeof value === 'string' ||
    typeof value === 'boolean'
  ) {
    return value;
  }
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (Array.isArray(value)) {
    return value.map((item, index) => parseJsonValue(item, `${name}[${index}]`));
  }
  const object = record(value, name);
  return Object.fromEntries(
    Object.entries(object).map(([key, item]) => [
      key,
      parseJsonValue(item, `${name}.${key}`),
    ]),
  );
}

function parseJsonObject(value: unknown, name: string): JsonObject {
  const parsed = parseJsonValue(value, name);
  if (parsed === null || Array.isArray(parsed) || typeof parsed !== 'object') {
    throw new TypeError(`${name} must be an object`);
  }
  return parsed;
}

function parseStringArray(value: unknown, name: string): string[] {
  if (!Array.isArray(value)) throw new TypeError(`${name} must be an array`);
  return value.map((item, index) => {
    if (typeof item !== 'string' || item.length === 0) {
      throw new TypeError(`${name}[${index}] must be a non-empty string`);
    }
    return item;
  });
}

function assertUnique(values: string[], label: string): void {
  const seen = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) throw new TypeError(`Duplicate ${label}: ${value}`);
    seen.add(value);
  }
}

export function parseSyncCursor(value: unknown): SyncCursor {
  const cursor = record(value, 'SyncCursor');
  if (cursor.version !== SYNC_PROTOCOL_VERSION) {
    throw new TypeError('SyncCursor.version must be 1');
  }
  return {
    version: SYNC_PROTOCOL_VERSION,
    position: stringField(cursor, 'position', 'SyncCursor'),
  };
}

export function parseSyncOperation(value: unknown): SyncOperation {
  const operation = record(value, 'SyncOperation');
  return {
    id: stringField(operation, 'id', 'SyncOperation'),
    entityType: stringField(operation, 'entityType', 'SyncOperation'),
    entityId: stringField(operation, 'entityId', 'SyncOperation'),
    kind: stringField(operation, 'kind', 'SyncOperation'),
    payload: parseJsonObject(operation.payload, 'SyncOperation.payload'),
    createdAt: stringField(operation, 'createdAt', 'SyncOperation'),
  };
}

export function parseOperationBatch(value: unknown): OperationBatch {
  const batch = record(value, 'OperationBatch');
  const operationsValue = batch.operations;
  if (!Array.isArray(operationsValue)) {
    throw new TypeError('OperationBatch.operations must be an array');
  }
  const operations = operationsValue.map(parseSyncOperation);
  assertUnique(
    operations.map(({ id }) => id),
    'operation id',
  );

  return {
    protocolVersion: versionField(batch, 'OperationBatch'),
    batchId: stringField(batch, 'batchId', 'OperationBatch'),
    clientId: stringField(batch, 'clientId', 'OperationBatch'),
    cursor:
      batch.cursor === undefined ? undefined : parseSyncCursor(batch.cursor),
    operations,
  };
}

export function parseRejectedOperation(value: unknown): RejectedOperation {
  const rejection = record(value, 'RejectedOperation');
  return {
    operationId: stringField(rejection, 'operationId', 'RejectedOperation'),
    code: enumField(
      rejection,
      'code',
      'RejectedOperation',
      OPERATION_REJECTION_CODES,
    ),
    message: stringField(rejection, 'message', 'RejectedOperation'),
    retryable: booleanField(rejection, 'retryable', 'RejectedOperation'),
  };
}

export function parseConflictRecord(value: unknown): ConflictRecord {
  const conflict = record(value, 'ConflictRecord');
  const parsed: ConflictRecord = {
    operationId: stringField(conflict, 'operationId', 'ConflictRecord'),
    entityType: stringField(conflict, 'entityType', 'ConflictRecord'),
    entityId: stringField(conflict, 'entityId', 'ConflictRecord'),
    reason: enumField(conflict, 'reason', 'ConflictRecord', CONFLICT_REASONS),
    clientVersion: nullableStringField(
      conflict,
      'clientVersion',
      'ConflictRecord',
    ),
    serverVersion: nullableStringField(
      conflict,
      'serverVersion',
      'ConflictRecord',
    ),
    message: stringField(conflict, 'message', 'ConflictRecord'),
  };
  if (conflict.serverRecord !== undefined) {
    parsed.serverRecord = parseJsonObject(
      conflict.serverRecord,
      'ConflictRecord.serverRecord',
    );
  }
  return parsed;
}

export function parseOperationResult(value: unknown): OperationResult {
  const result = record(value, 'OperationResult');
  const acceptedOperationIds = parseStringArray(
    result.acceptedOperationIds,
    'OperationResult.acceptedOperationIds',
  );
  assertUnique(acceptedOperationIds, 'accepted operation id');

  if (!Array.isArray(result.rejectedOperations)) {
    throw new TypeError('OperationResult.rejectedOperations must be an array');
  }
  const rejectedOperations = result.rejectedOperations.map(
    parseRejectedOperation,
  );
  const rejectedIds = rejectedOperations.map(({ operationId }) => operationId);
  assertUnique(rejectedIds, 'rejected operation id');

  for (const operationId of rejectedIds) {
    if (acceptedOperationIds.includes(operationId)) {
      throw new TypeError(
        `Operation ${operationId} cannot be both accepted and rejected`,
      );
    }
  }

  if (!Array.isArray(result.conflicts)) {
    throw new TypeError('OperationResult.conflicts must be an array');
  }
  const conflicts = result.conflicts.map(parseConflictRecord);
  assertUnique(
    conflicts.map(({ operationId }) => operationId),
    'conflict operation id',
  );
  for (const conflict of conflicts) {
    const rejection = rejectedOperations.find(
      ({ operationId }) => operationId === conflict.operationId,
    );
    if (rejection?.code !== 'conflict') {
      throw new TypeError(
        `Conflict ${conflict.operationId} must have a matching conflict rejection`,
      );
    }
  }

  return {
    protocolVersion: versionField(result, 'OperationResult'),
    batchId: stringField(result, 'batchId', 'OperationResult'),
    cursor: parseSyncCursor(result.cursor),
    acceptedOperationIds,
    rejectedOperations,
    conflicts,
  };
}

export * from './client';
export * from './transport';
